name: Typst Build

on:
  push:
    paths:
      - "versatile-apa/**"
      - "upsa-bo/**"
      - ".github/workflows/typst.yml"
  pull_request:
    branches:
      - main
    paths:
      - "versatile-apa/**"
      - "upsa-bo/**"
      - ".github/workflows/typst.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Typst
        run: |
          # Use a specific version for consistent builds
          sudo snap install typst --channel=latest/stable
          typst --version

      - name: Set up fonts
        run: sudo apt-get update && sudo apt-get install -y fonts-cascadia-code

      - name: Cache fonts
        uses: actions/cache@v3
        with:
          path: ~/.local/share/fonts
          key: ${{ runner.os }}-fonts-${{ hashFiles('**/*.ttf', '**/*.otf') }}

      - name: Compile templates
        id: compile
        run: |
          mkdir -p output
          echo "::group::Versatile APA"
          typst compile --root . versatile-apa/template/main.typ output/versatile-apa.pdf
          echo "::endgroup::"

          echo "::group::UPSA Bolivia: Estudio de Factibilidad"
          typst compile --root . upsa-bo/estudio-de-factibilidad/template/estudio-de-factibilidad.typ output/upsa-estudio-factibilidad.pdf
          echo "::endgroup::"

          echo "::group::UPSA Bolivia: Tesis"
          typst compile --root . upsa-bo/tesis/template/tesis.typ output/upsa-tesis.pdf
           echo "::endgroup::"

      - name: Upload compiled PDFs
        uses: actions/upload-artifact@v4
        with:
          name: typst-templates
          path: output/*.pdf
          retention-days: 7

      - name: Verify PDFs were created
        run: |
          for file in output/*.pdf; do
            if [ ! -s "$file" ]; then
              echo "Error: $file is empty or not generated"
              exit 1
            fi
          done
          echo "All PDFs successfully generated"
